name: notify copr frontend docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: Trigger Workflow
            uses: actions/github-script@v6
            with:
              github-token: ${{ secrets.PAT_TOKEN }}
              script: |
                github.rest.actions.createWorkflowDispatch({
                  owner: 'opensourceways',
                  repo: 'copr_docker',
                  workflow_id: 'frontend-publish.yml',
                  ref: 'main',
                })